# Generated by Django 3.2.12 on 2022-03-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('serial_id', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_button1', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button2', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button3', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button4', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button5', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button6', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button7', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button8', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button9', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button10', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button11', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button12', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button13', models.CharField(blank=True, max_length=255, null=True)),
                ('area_button14', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
