# Generated by Django 3.2.12 on 2022-03-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iotdevices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
