# Generated by Django 3.2.12 on 2022-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevices', '0003_alter_devices_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='user',
        ),
        migrations.AddField(
            model_name='devices',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
